var annotated_dup =
[
    [ "GRT", "namespace_g_r_t.html", "namespace_g_r_t" ],
    [ "matplotlibcpp", "namespacematplotlibcpp.html", "namespacematplotlibcpp" ],
    [ "ASCIISerialStream", "class_a_s_c_i_i_serial_stream.html", "class_a_s_c_i_i_serial_stream" ],
    [ "AudioFileStream", "class_audio_file_stream.html", "class_audio_file_stream" ],
    [ "AudioStream", "class_audio_stream.html", "class_audio_stream" ],
    [ "BaseSerialInputStream", "class_base_serial_input_stream.html", "class_base_serial_input_stream" ],
    [ "BinaryIntArraySerialStream", "class_binary_int_array_serial_stream.html", "class_binary_int_array_serial_stream" ],
    [ "CalibrateProcess", "class_calibrate_process.html", "class_calibrate_process" ],
    [ "CalibrateResult", "class_calibrate_result.html", "class_calibrate_result" ],
    [ "Calibrator", "class_calibrator.html", "class_calibrator" ],
    [ "FirmataStream", "class_firmata_stream.html", "class_firmata_stream" ],
    [ "InputStream", "class_input_stream.html", "class_input_stream" ],
    [ "InteractivePlot", "class_interactive_plot.html", "class_interactive_plot" ],
    [ "InteractiveTimeSeriesPlot", "class_interactive_time_series_plot.html", "class_interactive_time_series_plot" ],
    [ "IOStream", "class_i_o_stream.html", null ],
    [ "IOStreamVector", "class_i_o_stream_vector.html", null ],
    [ "LogEnergy", "class_log_energy.html", "class_log_energy" ],
    [ "MacOSKeyboardOStream", "class_mac_o_s_keyboard_o_stream.html", "class_mac_o_s_keyboard_o_stream" ],
    [ "MacOSMouseOStream", "class_mac_o_s_mouse_o_stream.html", "class_mac_o_s_mouse_o_stream" ],
    [ "ofApp", "classof_app.html", "classof_app" ],
    [ "ofConsoleFileLoggerChannel", "classof_console_file_logger_channel.html", "classof_console_file_logger_channel" ],
    [ "OscInputStream", "class_osc_input_stream.html", "class_osc_input_stream" ],
    [ "OStream", "class_o_stream.html", "class_o_stream" ],
    [ "OStreamVector", "class_o_stream_vector.html", "class_o_stream_vector" ],
    [ "Palette", "class_palette.html", "class_palette" ],
    [ "Plotter", "class_plotter.html", "class_plotter" ],
    [ "SerialStream", "class_serial_stream.html", "class_serial_stream" ],
    [ "Stream", "class_stream.html", "class_stream" ],
    [ "TcpInputStream", "class_tcp_input_stream.html", "class_tcp_input_stream" ],
    [ "TcpOStream", "class_tcp_o_stream.html", "class_tcp_o_stream" ],
    [ "TrainingDataManager", "class_training_data_manager.html", "class_training_data_manager" ],
    [ "TrainingDataManagerTest", "class_training_data_manager_test.html", "class_training_data_manager_test" ],
    [ "TrainingSampleCheckerResult", "class_training_sample_checker_result.html", "class_training_sample_checker_result" ],
    [ "TrainingSampleGuiListener", "class_training_sample_gui_listener.html", "class_training_sample_gui_listener" ],
    [ "Tuneable", "class_tuneable.html", "class_tuneable" ]
];